# Generated by Django 5.2.5 on 2026-02-19 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reconnect', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='enrollment_number',
            field=models.CharField(blank=True, default='', max_length=50, unique=True),
        ),
    ]
