# Generated by Django 6.0.2 on 2026-02-20 09:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reconnect', '0003_customuser_cgpa_customuser_date_of_birth_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('body', models.TextField()),
                ('importance', models.CharField(choices=[('info', 'Info'), ('urgent', 'Urgent'), ('opportunity', 'Opportunity'), ('event', 'Event Linked')], default='info', max_length=20)),
                ('display_day', models.CharField(help_text="Day number, e.g. '22'", max_length=10)),
                ('display_month', models.CharField(help_text="Month abbreviation, e.g. 'Feb'", max_length=10)),
                ('action_link', models.URLField(blank=True, default='', max_length=500)),
                ('action_label', models.CharField(blank=True, default='', max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_announcements', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('date_display', models.CharField(help_text="Display date, e.g. 'OCT 24, 2024'", max_length=50)),
                ('category', models.CharField(choices=[('Reunion', 'Reunion'), ('Networking', 'Networking'), ('Mentorship', 'Mentorship'), ('Placement', 'Placement'), ('Sports', 'Sports'), ('Seminar', 'Seminar'), ('Cultural', 'Cultural'), ('Other', 'Other')], default='Other', max_length=50)),
                ('image_url', models.URLField(blank=True, default='', max_length=500)),
                ('description', models.TextField(blank=True, default='')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EventTimelineItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.CharField(max_length=50)),
                ('activity', models.CharField(max_length=200)),
                ('order', models.PositiveIntegerField(default=0)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timeline', to='reconnect.event')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
